CREATE TABLE `yw_yanxue_student_apply_batch` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` bigint(20) NOT NULL COMMENT '申请用户ID（关联系统用户表）',
    `vipinfo_id` bigint(20) DEFAULT NULL COMMENT '关联会员单位信息表ID（yw_yanxue_vipinfo）',
    `apply_no` varchar(50) NOT NULL COMMENT '申请批次单号（唯一）',
    `apply_status` tinyint(4) DEFAULT '0' COMMENT '申请状态：0-草稿 1-待审核 2-审核通过 3-审核拒绝',
    `upload_file_path` varchar(500) DEFAULT NULL COMMENT '原始上传Excel文件OSS路径',
    `file_type` varchar(20) DEFAULT NULL COMMENT '文件类型',
    `parse_status` tinyint(4) DEFAULT '0' COMMENT '解析状态：0-未解析 1-解析成功 2-解析失败',
    `parse_error` varchar(500) DEFAULT NULL COMMENT '解析失败信息',
    `parse_count` int(11) DEFAULT '0' COMMENT '解析出的学生数量',
    `download_url` varchar(500) DEFAULT NULL COMMENT '审核通过后批量下载ZIP地址',
    `audit_remark` varchar(500) DEFAULT NULL COMMENT '审核备注/拒绝原因',
    `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
    `auditor_id` bigint(20) DEFAULT NULL COMMENT '审核人ID',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` tinyint(1) DEFAULT '0',
    `tenant_id` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_apply_no` (`apply_no`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_vipinfo_id` (`vipinfo_id`),
    KEY `idx_apply_status` (`apply_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学生证书申请批次表（上传Excel后形成一批待审核数据）';

CREATE TABLE `yw_yanxue_student_apply` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `apply_batch_id` bigint(20) NOT NULL COMMENT '关联申请批次表ID（yw_yanxue_student_apply_batch）',
    `user_id` bigint(20) NOT NULL COMMENT '申请用户ID（关联系统用户表）',
    `vipinfo_id` bigint(20) DEFAULT NULL COMMENT '关联会员单位信息表ID（yw_yanxue_vipinfo）',
    `student_name` varchar(100) NOT NULL COMMENT '学生姓名',
    `id_card` varchar(18) DEFAULT NULL COMMENT '身份证号码',
    `school_name` varchar(200) DEFAULT NULL COMMENT '学校名称',
    `class_name` varchar(100) DEFAULT NULL COMMENT '班级',
    `course_name` varchar(200) DEFAULT NULL COMMENT '课程名称',
    `course_hours` varchar(50) DEFAULT NULL COMMENT '学习课时',
    `course_provider` varchar(200) DEFAULT NULL COMMENT '课程实施方',
    `cert_date` date DEFAULT NULL COMMENT '落证时间',
    `stamp_unit` varchar(100) DEFAULT NULL COMMENT '落章单位',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` tinyint(1) DEFAULT '0',
    `tenant_id` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_apply_batch_id` (`apply_batch_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_student_name` (`student_name`),
    KEY `idx_id_card` (`id_card`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学生证书申请明细表（Excel解析后的逐学生申请数据）';

CREATE TABLE `yw_yanxue_cert_student` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `apply_detail_id` bigint(20) NOT NULL COMMENT '关联申请明细表ID（yw_yanxue_student_apply）',
    `user_id` bigint(20) NOT NULL COMMENT '所属会员用户ID',
    `vipinfo_id` bigint(20) DEFAULT NULL COMMENT '关联会员单位信息表ID',
    `cert_year` int(11) NOT NULL COMMENT '证书年度，用于编号和年度统计',
    `cert_no` varchar(50) NOT NULL COMMENT '证书编号（唯一，生成规则：CCPST+年份+序号）',
    `student_name` varchar(100) NOT NULL COMMENT '学生姓名',
    `id_card` varchar(18) DEFAULT NULL COMMENT '身份证号码',
    `school_name` varchar(200) DEFAULT NULL COMMENT '学校名称',
    `class_name` varchar(100) DEFAULT NULL COMMENT '班级',
    `course_name` varchar(200) DEFAULT NULL COMMENT '课程名称',
    `course_hours` varchar(50) DEFAULT NULL COMMENT '学习课时',
    `course_provider` varchar(200) DEFAULT NULL COMMENT '课程实施方',
    `cert_date` date DEFAULT NULL COMMENT '落证时间',
    `stamp_unit` varchar(100) DEFAULT NULL COMMENT '落章单位',
    `cert_image_url` varchar(500) DEFAULT NULL COMMENT '生成的证书图片OSS路径',
    `issue_time` datetime DEFAULT NULL COMMENT '证书生成时间',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` tinyint(1) DEFAULT '0',
    `tenant_id` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_cert_no` (`cert_no`),
    KEY `idx_apply_detail_id` (`apply_detail_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_cert_year` (`cert_year`),
    KEY `idx_student_name` (`student_name`),
    KEY `idx_id_card` (`id_card`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学生证书正式表（审核通过后生成）';

-- 可选优化：
-- 如果后续担心 CCPST+年份+序号 的并发唯一性，建议增加一张 yw_yanxue_cert_no_seq 年度序列表。
